### ISSUE TITLE
Feature Request: Support for T1015

### ISSUE THREAD

**Issue by hnlkaitan** [sebmos/node-eufy-api#15]
When a replacement model was sent to me, eufy's support team told me they'd be sending me the T1015 ("the upgraded model with a longer lifetime"), is there any way to add this model for homebridge support?

EDIT: It's the Tunable White Smart Bulb

**Comment by sebmos** [comment]
I added experimental support on the [T1015-support](https://github.com/sebmos/node-eufy-api/tree/T1015-support) branch. Can you check out that branch, run the CLI (see `README.md`) and see if that works for you?
If it does, I'll merge it into the main branch - otherwise I can at least update the README.md, so others know.

It's possible it simply won't work - I saw a comment somewhere suggesting that newer Eufy bulbs cannot be controlled via local socket connections anymore, only directly via the internet (which this package doesn't support).

**Comment by hnlkaitan** [comment]
I ran
```
git clone https://github.com/sebmos/node-eufy-api.git
cd node-eufy-api
git checkout T1015-support
npm install
npm run build
npm run cli
```

After inputting email and password, I got `No devices found, exiting`

Just wanted to make sure, that was the correct set of commands, right?

**Comment by sebmos** [comment]
Can you run it in verbose mode (`npm run cli:verbose`)?

**Comment by hnlkaitan** [comment]
I get
```
> node-eufy-api@0.3.2 cli:verbose /Users/hnlkaitan/Downloads/node-eufy-api
> node lib/cli.js --verbose

Logging in
Loading devices
Logged in, devices loaded
No devices found, exiting
```

**Comment by sebmos** [comment]
I pushed a change adding extra log messages to the initial connection - can you load them, run `npm run build` & `npm run cli:verbose`?

If there are extra messages, starting with "Device found:", can you post those? (And make sure to replace any information with "***" or so - it includes the device & room name, etc. This way I still know what information is there - the details are mostly unimportant.)

**Comment by hnlkaitan** [comment]
I attached the output here
[output.txt](https://github.com/sebmos/node-eufy-api/files/5301810/output.txt)

**Comment by sebmos** [comment]
Thanks! Unfortunately, the `local_code` key is missing in the `device` object - this is needed to send commands via socket. Sadly, it sounds like Eufy's newer devices don't support local control anymore. (Which is really frustrating - the socket-based control is much faster!)

**Comment by hnlkaitan** [comment]
That's a shame; thank you for helping me out with this though it means a lot!
